### ISSUE TITLE
panic when trying to connect to existing database

### ISSUE THREAD

**Issue by lucj** [acorn-io/mongodb-external#6]
I've created a MongoDB Atlas cluster and run an application which connects to this one.
The Acornfile I use:
```
services: db: {
	image: "ghcr.io/acorn-io/mongodb-external:v#.#.#"
}

containers: {
	app: {
		image: "lucj/counter:v0.1.0"
		ports: publish: "8000/http"
		env: {
			DB_HOST: "@{service.db.address}"
			DB_PORT: "@{service.db.port.27017}"
			DB_NAME: "@{service.db.data.dbName}"
			DB_USER: "@{service.db.secrets.user.username}"
			DB_PASS: "@{service.db.secrets.user.password}"
		}
	}
}

```

As describe in the doc, when I run this application, the CLI asked for the database address, credentials, and other info but once I entered these information I get the following error:
 
```
[db]; (service: db): acorn [counter.db] is not ready

  ## Overview                                                                 
                                                                              
  This will create the service from an existing MongoDB so that it can be     
  swapped with the MongoDB container service.                                 
                                                                              
  ## Instructions                                                             
                                                                              
  fill in:                                                                    
                                                                              
  • address: the address of the MongoDB server (mongo.example.com)            
  • port: the port of the MongoDB server (27017)                              
  • username: the username to use to connect to the MongoDB server            
  • password: the password to use to connect to the MongoDB server            
  • adminUsername: the username to use to connect to the MongoDB server as an 
  admin                                                                       
  • adminPassword: the password to use to connect to the MongoDB server as an 
  admin                                                                       
  • proto: the protocol to use to connect to the MongoDB server (mongodb or   
  mongodb+srv)                                                                
  • dbName: the name of the database to use                                   


? address ************************
? adminPassword ****************
? adminUsername **********
? dbName ****
? password ****************
? port (default: 27017) 
? proto (default: mongodb+srv) 
? username **********
? Choose an existing credential or enter a new one Existing: config-qd5mz (Keys: [address, adminPassword, adminUsername, dbName, password, port, proto, username], Created: [2024-02-03 17:44:38 +0100 CET])
? Credential [counter.db.config] is configured to [config-qd5mz], do you want to change it No
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x698 pc=0x1047f1d90]

goroutine 233 [running]:
github.com/acorn-io/runtime/pkg/login.Secrets({0x105ee92d0, 0x1400133c050}, {0x105f4cb28, 0x140004f1ce0}, 0x14000f37000)
        github.com/acorn-io/runtime/pkg/login/login.go:28 +0x120
github.com/acorn-io/runtime/pkg/login.loginApp({0x105ee92d0, 0x1400133c050}, {0x105f4cb28?, 0x140004f1ce0?}, {0x14000c45d70?, 0x1400111a478?})
        github.com/acorn-io/runtime/pkg/login/login.go:55 +0xa4
github.com/acorn-io/runtime/pkg/login.Secrets({0x105ee92d0, 0x1400133c050}, {0x105f4cb28, 0x140004f1ce0}, 0x14000d55000)
        github.com/acorn-io/runtime/pkg/login/login.go:38 +0x240
github.com/acorn-io/runtime/pkg/login.loginApp({0x105ee92d0, 0x1400133c050}, {0x105f4cb28?, 0x140004f1ce0?}, {0x140018508a0?, 0x14000ce6578?})
        github.com/acorn-io/runtime/pkg/login/login.go:55 +0xa4
github.com/acorn-io/runtime/pkg/login.Secrets({0x105ee92d0, 0x1400133c050}, {0x105f4cb28, 0x140004f1ce0}, 0x14000d55800)
        github.com/acorn-io/runtime/pkg/login/login.go:38 +0x240
github.com/acorn-io/runtime/pkg/login.loginApp({0x105ee92d0, 0x1400133c050}, {0x105f4cb28?, 0x140004f1ce0?}, {0x1400106ad80?, 0xc8?})
        github.com/acorn-io/runtime/pkg/login/login.go:55 +0xa4
github.com/acorn-io/runtime/pkg/login.Secrets({0x105ee92d0, 0x1400133c050}, {0x105f4cb28, 0x140004f1ce0}, 0x14000d54800)
        github.com/acorn-io/runtime/pkg/login/login.go:38 +0x240
github.com/acorn-io/runtime/pkg/log.(*DefaultLoggerImpl).AppStatus(0x14000df44c0, 0x14?, {0x14000a20f80, 0x74}, 0x14000c23701?)
        github.com/acorn-io/runtime/pkg/log/default_log.go:50 +0xf4
github.com/acorn-io/runtime/pkg/dev.PrintAppStatus(0x14000a20f00?, {0x105eae800, 0x14000df44c0})
        github.com/acorn-io/runtime/pkg/dev/dev.go:528 +0x54
github.com/acorn-io/runtime/pkg/dev.AppStatusLoop.func1(0x14000d54800)
        github.com/acorn-io/runtime/pkg/dev/dev.go:543 +0x1e8
github.com/acorn-io/baaah/pkg/watcher.retryWatch[...].func1()
        github.com/acorn-io/baaah@v0.0.0-20240119160309-2a58ee757bbd/pkg/watcher/watcher.go:104 +0x48
github.com/acorn-io/baaah/pkg/watcher.doWatch[...]({0x105ee92d0, 0x1400133c050}, {0x14000b94000, 0x105f1ce38?}, 0x1020f29c4?, 0x14000ae5ae8?)
        github.com/acorn-io/baaah@v0.0.0-20240119160309-2a58ee757bbd/pkg/watcher/watcher.go:78 +0x3e4
github.com/acorn-io/baaah/pkg/watcher.retryWatch[...]({0x105ee92d0, 0x1400133c050}, {0x14000b94000, 0x140008e6000?}, 0x140011de020?, 0x140012f9b78?)
        github.com/acorn-io/baaah@v0.0.0-20240119160309-2a58ee757bbd/pkg/watcher/watcher.go:108 +0xac
github.com/acorn-io/baaah/pkg/watcher.(*Watcher[...]).bySelector(0x105f147a0, {0x105ee92d0, 0x1400133c050?}, {0x14000a2c488, 0x5}, {0x0, 0x0?}, {0x105ef76a8, 0x140010c4000?}, 0x14000fa0030)
        github.com/acorn-io/baaah@v0.0.0-20240119160309-2a58ee757bbd/pkg/watcher/watcher.go:209 +0x314
github.com/acorn-io/baaah/pkg/watcher.(*Watcher[...]).ByName(0x105f147a0?, {0x105ee92d0, 0x1400133c050}, {0x14000a2c488, 0x5}, {0x14001412ed0, 0x7}, 0x14000ad66f8)
        github.com/acorn-io/baaah@v0.0.0-20240119160309-2a58ee757bbd/pkg/watcher/watcher.go:168 +0x2b8
github.com/acorn-io/runtime/pkg/dev.AppStatusLoop({0x105ee92d0, 0x1400133c050}, {0x105f4cb28, 0x140004f1ce0}, {0x105eae800?, 0x14000df44c0}, {0x14001412ed0, 0x7})
        github.com/acorn-io/runtime/pkg/dev/dev.go:538 +0x188
github.com/acorn-io/runtime/pkg/wait.App.func1()
        github.com/acorn-io/runtime/pkg/wait/wait.go:29 +0x138
created by github.com/acorn-io/runtime/pkg/wait.App in goroutine 1
        github.com/acorn-io/runtime/pkg/wait/wait.go:27 +0x194
(venv) (⎈|kind-k8s:N/A)luc@jupiter local-and-externa-databases % 
```

**Comment by lucj** [comment]
No more panic with 0.10.1 rc2
